name: autobuild

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build image job
        steps:
            - name: Checkout master
              uses: actions/checkout@master
            - name: Build and publish image
              uses: ilteoood/docker_buildx@master
              with:
                publish: true
                dockerUser: ${{ secrets.DOCKERHUB_USERNAME }}
                dockerPassword: ${{ secrets.DOCKERHUB_TOKEN }}
                context: ./image-builder
                platforms: linux/amd64,linux/arm64
                imageName: barton0426/docker-flexget-autoremove-torrents-plugin:latest
